# Используем базовый образ от Playwright
FROM node:18
# Создание рабочей директории внутри контейнера
WORKDIR /usr/src/app
# Копирование package.json, package-lock.json.
COPY package*.json ./
# Установка необходимых зависимостей
RUN npm install
# Копирование всех необходимых файлов проекта в контейнер
COPY . .
# Установка браузеров Playwright
RUN npx playwright install --with-deps
# Команда для запуска тестов
CMD ["npx", "playwright", "test", "--grep=demoqa.textbox.spec.ts"]
