name: Playwright Tests triggered manually
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
     #Создаем Docker image
    - name: Built Docker image 
    - run: docker build -t playwright-tests -f Dockerfile.custom .
    # Запуск Docker Container и запуск тестов в нем
    - name: Run Docker container with Playwright tests
    - run: docker run playwright-tests
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
