name: Playwright Tests triggered on push
on:
  push:
    branches:  
    - main
  pull_request:
    branches: 
    - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    #Создаем Docker image
    - name: Built Docker image using official image
      run: docker build -f Dockerfile.official .
    # Запуск Docker Container и запуск тестов в нем
    - name: Run Docker container with Playwright tests
      run: docker run mcr.microsoft.com/playwrigh
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30